//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPet.Plugin.DemoClock.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPet.Plugin.DemoClock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 中华人民共和国#100000:|
        ///北京市#110000:|010
        ///东城区#110101:|010
        ///西城区#110102:|010
        ///朝阳区#110105:|010
        ///丰台区#110106:|010
        ///石景山区#110107:|010
        ///海淀区#110108:|010
        ///门头沟区#110109:|010
        ///房山区#110111:|010
        ///通州区#110112:|010
        ///顺义区#110113:|010
        ///昌平区#110114:|010
        ///大兴区#110115:|010
        ///怀柔区#110116:|010
        ///平谷区#110117:|010
        ///密云区#110118:|010
        ///延庆区#110119:|010
        ///天津市#120000:|022
        ///和平区#120101:|022
        ///河东区#120102:|022
        ///河西区#120103:|022
        ///南开区#120104:|022
        ///河北区#120105:|022
        ///红桥区#120106:|022
        ///东丽区#120110:|022
        ///西青区#120111:|022
        ///津南区#120112:|022
        ///北辰区#120113:|022
        ///武清区#120114:|022        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string V3CityADCODE_lps {
            get {
                return ResourceManager.GetString("V3CityADCODE_lps", resourceCulture);
            }
        }
    }
}
